[package]
name = "hecto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html44444444444444444444444444444444433333333333333333

[dependencies]
termion = "1"
unicode-segmentation = "1"